#!/usr/bin/env bash
# Configure ubuntu server to show holberton school port 80
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Page not found"  > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Laracious permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/^\tlocation \/ {/\tlocation \/ {\n\t\tadd_header X-Served-By '$HOSTNAME';/" /etc/nginx/sites-available/default
service nginx restart
